version: "3"
services:
  SparkHelloWorld:
    image: spark/hotel-weather-job
    build:
      args:
        spark_master: "k8s://https://domain:port"

        blob_read_account_name: "<blob_read_account_name>"
        blob_read_container_name: "<blob_read_container_name>"
        blob_read_container_key: "<blob_read_container_key>"

        blob_write_account_name: "<blob_write_account_name>"
        blob_write_container_name: "<blob_write_container_name>"
        blob_write_container_key: "<blob_write_container_key>"

        opencage_api_key: "<opencage_api_key>"

      context: ""
      dockerfile: Dockerfile
    container_name: HotelWeatherJob