version: "3"
services:
  SparkHelloWorld:
    image: spark/hotel-weather-job
    build:
      args:
        spark_master: "k8s://https://kubernetes.docker.internal:6443"

        blob_read_account_name: "bd201stacc"
        blob_read_container_name: "m6sparkbasics"
        blob_read_container_key: "L6X661FhSG78rVrWUyNOTzeXyzfHzQVZF9bX0ukUS4U90VQdLTeuEVWUFiok8l4MAXJGMLYIolTT1R1rjuNtrA=="

        blob_write_account_name: "eldarbigdata"
        blob_write_container_name: "hotel-weather"
        blob_write_container_key: "TNYRQlRounWUyl3qAMLYLto21nVYb2P2oPwPYKzzAGnuKYQCoDaxUUt8NcLmtWKbWQYd027rMx+frV23nDacpA=="

        opencage_api_key: "8b8ee57729df4c2796987adb5b9fd153"

      context: ""
      dockerfile: Dockerfile
    container_name: HotelWeatherJob