apiVersion: v1
kind: Secret
metadata:
  labels:
     heritage: {{ .Release.Service }}
     release: {{ .Release.Name }}
     chart: {{ template "confluent-operator.chart" . }}
     app: {{ template "confluent-operator.name" . }}
  namespace: {{ .Release.Namespace }}
  name: {{ .Values.name }}-apikeys
type: Opaque
data:
  apikeys.json : {{ include "kafka.sasl_users" . | b64enc }}
  {{- include "confluent-operator.global-sasl-secret" . | indent 2 }}
  {{- if .Values.tls.jksPassword}}
  jksPassword.txt: {{ (printf "jksPassword=%s" .Values.tls.jksPassword) | b64enc }}
  {{- end }}
  license.txt: {{ (printf "license=%s" .Values.license) | b64enc }}
  {{- if .Values.global.authorization.rbac.enabled }}
  {{- $_ := required "ldap credential connot be empty" .Values.services.mds.ldap.authentication.simple.credentials }}
  {{- $_ := required "ldap principal cannot be empty." .Values.services.mds.ldap.authentication.simple.principal }}
  ldap.txt: {{ (printf "credentials=%s\nprincipal=%s" .Values.services.mds.ldap.authentication.simple.credentials .Values.services.mds.ldap.authentication.simple.principal ) | b64enc }}
  {{- include "kafka.mds-credential-secret" . | indent 2 }}
  {{- end }}
