{{- if and .Values.global.provider.storage (not .Values.storageClassName) }}
{{- if eq (len $.Values.global.provider.kubernetes.deployment.zones) 0 }}
{{- fail "Provide at least 1 zone information for .Values.global.provider.kubernetes.deployment.zones " }}
{{- end }}
{{- $_ := required "Name of zookeeper cluster is required." $.Values.name }}
apiVersion: v1
items:
{{- range $i, $e := .Values.global.provider.kubernetes.deployment.zones }}
- apiVersion: storage.k8s.io/v1
  kind: StorageClass
  metadata:
  {{- include "confluent-operator.labels" $  | indent 2 }}
    annotations:
{{ toYaml $.Values.global.provider.storage.annotations | trim | indent 6 }}
    name: {{ $.Values.name }}-standard-ssd-{{ $e }}
    namespace: ""
  {{- if hasKey $.Values.global.provider.storage "parameters" }}
  parameters:
{{ toYaml $.Values.global.provider.storage.parameters | trim | indent 4 }}
  {{- end }}
  {{- if hasKey $.Values.global.provider.storage "provisioner" }}
  provisioner: {{ $.Values.global.provider.storage.provisioner }}
  {{- end }}
  {{- if hasKey $.Values.global.provider.storage "reclaimPolicy" }}
  reclaimPolicy: {{ $.Values.global.provider.storage.reclaimPolicy }}
  {{- end }}
  {{- if hasKey $.Values.global.provider.storage "mountOptions" }}
  {{- if (gt (len $.Values.global.provider.storage.mountOptions) 0) }}
  mountOptions:
{{ toYaml $.Values.global.provider.storage.mountOptions | trim | indent 2 }}
  {{- end }}
  {{- end }}
  {{- if hasKey $.Values.global.provider.storage "volumeBindingMode" }}
  {{- if not (empty $.Values.global.provider.storage.volumeBindingMode) }}
  volumeBindingMode: {{ $.Values.global.provider.storage.volumeBindingMode }}
  {{- end }}
  {{- end }}
  {{- if hasKey $.Values.global.provider.storage "allowedTopologies" }}
  {{- if (gt (len $.Values.global.provider.storage.allowedTopologies)  0) }}
  allowedTopologies:
{{ toYaml $.Values.global.provider.storage.allowedTopologies | trim | indent 2 }}
  {{- end }}
  {{- end }}
  {{- if hasKey $.Values.global.provider.storage "allowVolumeExpansion" }}
  {{- if not (empty $.Values.global.provider.storage.allowVolumeExpansion) }}
  allowVolumeExpansion: {{ $.Values.global.provider.storage.allowVolumeExpansion }}
  {{- end }}
  {{- end }}
{{- end }}
kind: List
{{- end }}
