apiVersion: v1
kind: Secret
metadata:
  {{- include "confluent-operator.labels" . }}
  namespace: {{ .Release.Namespace }}
  name: {{ .Values.name }}-apikeys
type: Opaque
data:
  apikeys.json : {{ include "confluent-operator.apikeys" . | b64enc }}
  jksPassword.txt: {{ (printf "jksPassword=%s" .Values.tls.jksPassword) | b64enc }}
  license.txt: {{ (printf "license=%s" .Values.license)  | b64enc }}
  {{- include "confluent-operator.global-sasl-secret" . | indent 2 }}
  {{- include "confluent-operator.mds-credential-secret" . | indent 2 }}
