{{ include "confluent-operator.cert-required" . }}
apiVersion: v1
kind: Secret
metadata:
  {{- include "confluent-operator.labels" . }}
  namespace: {{ .Release.Namespace }}
  name: {{ .Values.name }}-sslcerts
type: Opaque
data:
  {{- if .Values.tls.fullchain }}
  fullchain.pem: {{ .Values.tls.fullchain | b64enc }}
  {{- end }}
  {{- if .Values.tls.privkey }}
  privkey.pem: {{ .Values.tls.privkey | b64enc }}
  {{- end }}
  {{- if .Values.tls.cacerts }}
  cacerts.pem: {{ .Values.tls.cacerts | b64enc }}
  {{- end }}
  {{- include "confluent-operator.mds-publickey" . | indent 2 }}