apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    controller-tools.k8s.io: "1.0"
  name: zookeeperclusters.cluster.confluent.com
spec:
  group: cluster.confluent.com
  names:
    categories:
    - all
    kind: ZookeeperCluster
    plural: zookeeperclusters
    shortNames:
    - zk
    - zookeeper
  scope: Namespaced
  subresources:
    scale:
      specReplicasPath: .spec.replicas
      statusReplicasPath: .status.replicas
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            configOverrides:
              properties:
                jvm:
                  items:
                    type: string
                  type: array
                log4j:
                  items:
                    type: string
                  type: array
                server:
                  items:
                    type: string
                  type: array
              type: object
            image:
              pattern: .+:.+
              type: string
            initContainers:
              items:
                properties:
                  args:
                    items:
                      type: string
                    type: array
                  command:
                    items:
                      type: string
                    type: array
                  envVar:
                    type: object
                  image:
                    pattern: .+:.+
                    type: string
                  name:
                    type: string
                required:
                - name
                - image
                - command
                type: object
              type: array
            internalKubDomain:
              type: string
            jvmConfig:
              properties:
                heapSize:
                  pattern: ^[0-9]+[M,GB,m,g]{1,2}$
                  type: string
              required:
              - heapSize
              type: object
            mountedSecrets:
              items:
                properties:
                  keyItems:
                    description: 'Cannot have ''items'' field in CRD: https://github.com/kubernetes/kubernetes/issues/68466'
                    items:
                      properties:
                        key:
                          minLength: 1
                          type: string
                        path:
                          minLength: 1
                          type: string
                      required:
                      - key
                      - path
                      type: object
                    type: array
                  secretRef:
                    minLength: 1
                    type: string
                required:
                - secretRef
                type: object
              type: array
            placement:
              properties:
                affinity:
                  properties:
                    nodeAffinity:
                      properties:
                        key:
                          maxLength: 64
                          minLength: 1
                          type: string
                        rule:
                          enum:
                          - PREFERRED
                          - REQUIRED
                          type: string
                        values:
                          items:
                            type: string
                          minItems: 1
                          type: array
                      required:
                      - key
                      - values
                      type: object
                    podAffinity:
                      properties:
                        rule:
                          enum:
                          - PREFERRED
                          - REQUIRED
                          type: string
                        terms:
                          items:
                            properties:
                              key:
                                maxLength: 64
                                minLength: 1
                                type: string
                              namespaces:
                                items:
                                  type: string
                                type: array
                              topologyKey:
                                properties:
                                  key:
                                    type: string
                                required:
                                - key
                                type: object
                              values:
                                items:
                                  type: string
                                minItems: 1
                                type: array
                              weight:
                                properties:
                                  weight:
                                    format: int32
                                    maximum: 100
                                    minimum: 1
                                    type: integer
                                required:
                                - weight
                                type: object
                            required:
                            - key
                            - values
                            type: object
                          type: array
                      required:
                      - terms
                      type: object
                    podAntiAffinity:
                      properties:
                        rule:
                          enum:
                          - PREFERRED
                          - REQUIRED
                          type: string
                        terms:
                          items:
                            properties:
                              key:
                                maxLength: 64
                                minLength: 1
                                type: string
                              namespaces:
                                items:
                                  type: string
                                type: array
                              topologyKey:
                                properties:
                                  key:
                                    type: string
                                required:
                                - key
                                type: object
                              values:
                                items:
                                  type: string
                                minItems: 1
                                type: array
                              weight:
                                properties:
                                  weight:
                                    format: int32
                                    maximum: 100
                                    minimum: 1
                                    type: integer
                                required:
                                - weight
                                type: object
                            required:
                            - key
                            - values
                            type: object
                          type: array
                      required:
                      - terms
                      type: object
                  type: object
                disableHostPort:
                  type: boolean
                nodeAffinity:
                  properties:
                    key:
                      maxLength: 64
                      minLength: 1
                      type: string
                    rule:
                      enum:
                      - PREFERRED
                      - REQUIRED
                      type: string
                    values:
                      items:
                        type: string
                      minItems: 1
                      type: array
                  required:
                  - key
                  - values
                  type: object
                oneReplicaPerNode:
                  type: boolean
                rack:
                  properties:
                    topology:
                      type: string
                  type: object
              type: object
            podAnnotations:
              type: object
            podSecurityContext:
              properties:
                fsGroup:
                  format: int64
                  type: integer
                randomUID:
                  type: boolean
                runAsGroup:
                  format: int64
                  type: integer
                runAsNonRoot:
                  type: boolean
                runAsUser:
                  format: int64
                  type: integer
                seLinuxOptions:
                  properties:
                    level:
                      type: string
                    role:
                      type: string
                    type:
                      type: string
                    user:
                      type: string
                  type: object
                supplementalGroups:
                  items:
                    format: int64
                    type: integer
                  type: array
                sysctls:
                  items:
                    properties:
                      name:
                        type: string
                      value:
                        type: string
                    required:
                    - name
                    - value
                    type: object
                  type: array
              type: object
            replicas:
              exclusiveMinimum: true
              format: int32
              type: integer
            resources:
              properties:
                limits:
                  properties:
                    cpu:
                      pattern: ^[0-9\.]+[m]?$
                      type: string
                    memory:
                      pattern: ^[0-9]+[E,P,T,G,M,K,Ei,Pi,Ti,Gi,Mi,Ki]{1,2}$
                      type: string
                  required:
                  - cpu
                  - memory
                  type: object
                requests:
                  properties:
                    cpu:
                      pattern: ^[0-9\.]+[m]?$
                      type: string
                    memory:
                      pattern: ^[0-9]+[E,P,T,G,M,K,Ei,Pi,Ti,Gi,Mi,Ki]{1,2}$
                      type: string
                  required:
                  - cpu
                  - memory
                  type: object
                storage:
                  items:
                    properties:
                      capacity:
                        pattern: ^[0-9]+[E,P,T,G,M,K,Ei,Pi,Ti,Gi,Mi,Ki]{1,2}$
                        type: string
                      name:
                        enum:
                        - data
                        - data0
                        - log
                        - txnlog
                        maxLength: 10
                        minLength: 1
                        type: string
                      storageClassName:
                        type: string
                      type:
                        format: int32
                        type: integer
                    required:
                    - capacity
                    - name
                    type: object
                  minItems: 1
                  type: array
              required:
              - requests
              - storage
              type: object
            serviceAccountName:
              type: string
            terminationGracePeriodInSecond:
              format: int64
              minimum: 30
              type: integer
            tls:
              properties:
                jmxAuthentication:
                  properties:
                    type:
                      enum:
                      - tls
                      type: string
                  required:
                  - type
                  type: object
                jmxTLS:
                  type: boolean
              type: object
            zones:
              items:
                type: string
              type: array
          required:
          - replicas
          - image
          - resources
          - jvmConfig
          - initContainers
          type: object
        status:
          properties:
            alternateEndpoint:
              type: string
            clusterName:
              type: string
            config:
              type: object
            currentReplicas:
              format: int32
              type: integer
            endpoints:
              type: string
            jmxSecurityProtocol:
              enum:
              - tls
              - mtls
              type: string
            phase:
              type: string
            readyReplicas:
              format: int32
              type: integer
            reason:
              type: string
            replicas:
              format: int32
              type: integer
          required:
          - phase
          - replicas
          - currentReplicas
          - readyReplicas
          type: object
  version: v1alpha1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
