{{- if or .Values.namespaced (and (not .Values.namespaced) .Values.installClusterResources) }}
apiVersion: rbac.authorization.k8s.io/v1
{{- if .Values.namespaced }}
kind: Role
{{- else }}
kind: ClusterRole
{{- end }}
metadata:
  {{- include "confluent-operator.labels" . }}
  name: {{ .Values.name }}
  {{- if .Values.namespaced }}
  namespace: {{ .Release.Namespace }}
  {{- end }}
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  - events
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - cluster.confluent.com
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - operator.confluent.cloud
  resources:
  - '*'
  verbs:
  - '*'
{{- if and (not .Values.namespaced) (.Values.installClusterResources) }}
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  - customresourcedefinitions/status
  verbs:
  - '*'
{{- end }}
- apiGroups:
  - cluster.confluent.com
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - policy
  resources:
  - poddisruptionbudgets
  verbs:
  - '*'
- apiGroups:
  - apps
  resources:
  - deployments
  - deployments/scale
  - deployments/status
  - replicasets
  - replicasets/scale
  - replicasets/status
  - statefulsets
  - statefulsets/scale
  - statefulsets/status
  verbs:
  - '*'
- apiGroups:
  - ""
  resources:
  - configmaps
  - endpoints
  - events
  - persistentvolumeclaims
  - pods
  - pods/exec
  - secrets
  - services
  verbs:
  - '*'
{{- end }}
