{{- if or .Values.namespaced (and (not .Values.namespaced) .Values.installClusterResources) }}
{{- if .Values.namespaced }}
kind: RoleBinding
{{- else }}
kind: ClusterRoleBinding
{{- end }}
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  {{- include "confluent-operator.labels" . }}
  name: {{ .Release.Namespace }}-{{ .Values.name }}
  {{- if .Values.namespaced }}
  namespace: {{ .Release.Namespace }}
  {{- end }}
subjects:
- kind: ServiceAccount
  name: {{ .Values.name }}
  namespace: {{ .Release.Namespace }}
roleRef:
  {{- if .Values.namespaced }}
  kind: Role
  {{- else }}
  kind: ClusterRole
  {{- end }}
  name: {{ .Values.name }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}
