apiVersion: v1
kind: Secret
metadata:
  {{- include "confluent-operator.labels" . }}
  namespace: {{ .Release.Namespace }}
  name: operator-licensing
type: Opaque
data:
  {{- if .Values.licenseKey }}
  licenseKey: {{ .Values.licenseKey | b64enc }}
  {{- end }}
  publicKey: {{ .Values.publicKey | b64enc }}
